version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.6.0
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.6.0
    restart: always
    environment:
      ELASTICSEARCH_URL: "127.0.0.1:9200"
      I18N_LOCALE: "zh-CN"
    ports:
      - "5601:5601"



version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ../elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.6.2
    restart: always
    networks:
      - elk #������ʽ
    environment:
      ELASTICSEARCH_URL: "127.0.0.1:9200"
      I18N_LOCALE: "zh-CN"
    ports:
      - "5601:5601"
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: always
    networks:
      - elk
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
networks:
  elk:
